name: daily_tracker_diet_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  stop_watch_timer: 0.7.0
  toggle_switch: ^0.1.8
  lite_rolling_switch: ^0.1.1
  cupertino_icons: ^1.0.0
  flutter_linkify: ^3.1.3
  url_launcher: ^5.7.2
  table_calendar: ^2.3.3
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  provider: ^4.0.1
  image_picker: ^0.6.7+4
  firebase_storage: ^2.1.0
  #path: ^1.6.0
  #uuid: ^1.0.1
  path: ^1.8.0
  uuid: ^3.0.0
  liquid_pull_to_refresh: ^2.0.0
 # flutter_form_builder: ^6.0.0-nullsafety.0
  charts_flutter: ^0.6.0
  animated_text_kit: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
  #sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - google_fonts/


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Bold.ttf
    - family: CairoL
      fonts:
        - asset: fonts/Cairo-Light.ttf
    - family: RobotoL
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: Shadows
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf
    - family: cairoSemiBold
      fonts:
        - asset: fonts/Cairo-SemiBold.ttf






